services:
  waha:
    image: devlikeapro/waha
    container_name: higertech-waha
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - WAHA_ZIP_LOGS=true
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
    volumes:
      - waha_sessions:/app/.sessions

volumes:
  waha_sessions:

